# Generated by Django 5.2.5 on 2025-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'login_credential',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50)),
                ('cost_category_project_type', models.CharField(max_length=100)),
                ('cost_centre_client_name', models.CharField(max_length=100)),
                ('issue_id', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Not Started'), ('2', 'Work In Progress'), ('3', 'Completed')], max_length=1)),
                ('issue_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_master',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('managers', models.ManyToManyField(blank=True, db_table='employee_manager_mapping', related_name='team_members', to='core.employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('work_date', models.DateField()),
                ('work_day', models.IntegerField()),
                ('project_code', models.CharField(max_length=50)),
                ('cost_category', models.CharField(max_length=100)),
                ('cost_centre', models.CharField(max_length=100)),
                ('issue_id', models.CharField(max_length=50)),
                ('manager_name', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Work In Progress', 'Work In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('shared_with', models.ManyToManyField(blank=True, db_table='attendance_shared_with', help_text='Employees with whom this ticket is shared', related_name='shared_tickets', to='core.logincredential')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
