# Generated by Django 5.2.5 on 2025-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('MANAGER', 'MANAGER'), ('EMPLOYEE', 'EMPLOYEE')], default='EMPLOYEE', max_length=20),
        ),
    ]
